### ISSUE TITLE
Replace the map

### ISSUE THREAD

**Issue by mehdibo** [mehdibo/coronamap-ma#12]
The map used currently by Openstreetmap has the Moroccan sahara separated, it would be better if someone has a replacement.

**Comment by ReversableCode** [comment]
What about this one: https://www.maptiler.com/maps/#basic//vector/4.11/-7.62/32.81
It doesn't look like it is separating morocco.

**Comment by mehdibo** [comment]
They actually do

**Comment by hchandad** [comment]
How about this [one](https://user-images.githubusercontent.com/10903202/76940209-1d3ef780-68fa-11ea-9fb3-93df79353cf1.png) : url format `https://tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png`

**Comment by mehdibo** [comment]
It has the same line splitting the Sahara

**Comment by mehdibo** [comment]
Used an image overlay

7ff5d1c6cdcb25efc8848e29037d02bace1e0097
