### ISSUE TITLE
5 New cases on 03/18/2020

### ISSUE THREAD

**Issue by ismailCodes** [mehdibo/coronamap-ma#19]
2 Agadir
2 Casablanca
1 Meknes

**Comment by ReversableCode** [comment]
[Source](https://m.hespress.com/societe/463687.html)

**Comment by ismailCodes** [comment]
SOURCE : [MAP MAROC](http://www.mapnews.ma/fr/actualites/politique/covid-19-cinq-nouveaux-cas-confirm%C3%A9s-au-maroc-minist%C3%A8re-de-la-sant%C3%A9)

**Comment by mehdibo** [comment]
4026f2725615a3a651a0362b0f84f3ecaa644b6d
