### ISSUE TITLE
5 New cases  18/03/2020

### ISSUE THREAD

**Issue by ybenbrai** [mehdibo/coronamap-ma#23]
1. https://fr.hespress.com/134491-ait-taleb-annonce-54-cas-confirmes-de-coronavirus-au-maroc.html

2. https://www.hespress.com/societe/463822.html
3. https://tanja24.com/%D9%88%D8%B2%D8%A7%D8%B1%D8%A9-%D8%A7%D9%84%D8%B5%D8%AD%D8%A9-54-%D8%AD%D8%A7%D9%84%D8%A9-%D9%85%D8%A4%D9%83%D8%AF%D8%A9-%D9%84%D9%81%D9%8A%D8%B1%D9%88%D8%B3-%D9%83%D9%88%D8%B1%D9%88%D9%86%D8%A7/

**Comment by mehdibo** [comment]
Thanks for reporting! can you change the title to include today's date?

**Comment by ybenbrai** [comment]
Like that ?

**Comment by ybenbrai** [comment]
Should i close the issue or what, sorry am new here

**Comment by mehdibo** [comment]
Yes, all the cases are by region, I have cities, if you have any other source that would be much appreciated. Thanks.

No just leave it open, I'll take care of it.

**Comment by ybenbrai** [comment]
I only have that sources, and i saw it on the news right now also , it’s available on ministry of health Facebook page also but its not professional job to share it as a source

**Comment by ReversableCode** [comment]
http://mapanticorona.map.ma/ar/node/265
@mehdibo They have the exact number per city

**Comment by mehdibo** [comment]
@ReversableCode those are regions not cities

**Comment by ReversableCode** [comment]
oh I didn't pay attention.

**Comment by ybenbrai** [comment]
For the moment the government only share cases by regions for some reasons, my sources had lack of location cause i shared early you can check now it’s already updated

**Comment by mehdibo** [comment]
05ff54a5662b17b9ecd2e90b1aa25ebf341da111
