### ISSUE TITLE
1 Case Healed on 19/03/2020 15:30

### ISSUE THREAD

**Issue by ybenbrai** [mehdibo/coronamap-ma#27]
Source :
https://m.hespress.com/societe/463929.html

**Comment by mehdibo** [comment]
b223a8def614d382d5703582f9e179abfce84ba8

**Comment by ybenbrai** [comment]
@mehdibo u didn’t add this case, can i have the link for the website?

**Comment by mehdibo** [comment]
I did [here](https://github.com/mehdibo/coronamap-ma/commit/b223a8def614d382d5703582f9e179abfce84ba8)

The website is in the repo's description:
https://github.com/mehdibo/coronamap-ma
