### ISSUE TITLE
1 New case on 19/03/2020 at 20:00

### ISSUE THREAD

**Issue by ybenbrai** [mehdibo/coronamap-ma#28]
Source : 
https://m.hespress.com/societe/463997.html

**Comment by mehdibo** [comment]
Thank you! I'll wait for the region

**Comment by ybenbrai** [comment]
@mehdibo like i said before they don’t tell the region any more for some private reasons.

**Comment by mehdibo** [comment]
@khimya They do here: http://covidmaroc.ma/ but they still didn't update it

**Comment by mehdibo** [comment]
0b684367362383e6bcc2041e785965a77a17c3e8
