### ISSUE TITLE
Automatic extract data from the official website 

### ISSUE THREAD

**Issue by 0xPacman** [mehdibo/coronamap-ma#33]
i believe it would be better if you could just extract data from [the official website](http://covidmaroc.sante.gov.ma) automatically without the need of manual input.

**Comment by mehdibo** [comment]
Yes I totally agree with you, I wanted to do it but unfortunately I don't have the time right now.

**Comment by mehdibo** [comment]
@ReversableCode [is working on this I think](https://github.com/mehdibo/coronamap-ma/pull/37)

**Comment by ReversableCode** [comment]
@mehdibo can this be marked as solved or is there still something else ?

**Comment by mehdibo** [comment]
Not yet, I will once everything is working smoothly

**Comment by mehdibo** [comment]
3a220c98f402905acc461fbb792b7d5dfa4ee33e
