### ISSUE TITLE
3 New cases on 20/03/2020 19:00

### ISSUE THREAD

**Issue by ybenbrai** [mehdibo/coronamap-ma#34]
Sources: 
https://m.hespress.com/societe/464156.html

**Comment by mehdibo** [comment]
fdd49e4c7a151a171e032d052b6ffc248e279abb

**Comment by ybenbrai** [comment]
Should i keep helping or u automated that?

**Comment by mehdibo** [comment]
I still didn't automate it, but I will. For the meantime your help is much appreciated!
