### ISSUE TITLE
Deaths and recoveries fetching is buggy

### ISSUE THREAD

**Issue by mehdibo** [mehdibo/coronamap-ma#43]
@ReversableCode

**Comment by ReversableCode** [comment]
I am working on it. God I hate aspx

**Comment by ReversableCode** [comment]
@mehdibo The problem is that each time they update the data. They go on and change the code again. The problem this time is that they were using span to show the numbers but they decided to change it to <font> all of a sudden. At least it's easier now to fetch than before.

**Comment by ReversableCode** [comment]
they changed span to font

**Comment by mehdibo** [comment]
I see, well they have to stop at one point, so might work after some fails.

#44
