### ISSUE TITLE
New cases on 17/03/2020

### ISSUE THREAD

**Issue by ReversableCode** [mehdibo/coronamap-ma#9]
[Source](https://www.hespress.com/societe/463646.html)

**Comment by ReversableCode** [comment]
Closed as they have already been reported.

**Comment by ReversableCode** [comment]
Reopened because the other report didn't have a source.

**Comment by mehdibo** [comment]
I added them locally, but I have a total of 43, there is one case missing from my side :(

The current live one has 37, it should have 38 I think

**Comment by mehdibo** [comment]
6a0e2e7d08d07fad429f6cb1bcbdbd141c91c4e7

**Comment by ReversableCode** [comment]
Regarding the case that you are missing, maybe it's this one: https://www.hespress.com/societe/463522.html
Since he came from France and was transported to Casablanca.
